# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague
---
/**:
  ros__parameters:
    # Configuration Settings for the Rover Rx
    device: tcp://septentrio:28784
    serial:
      baudrate: 921600
      hw_flow_control: "off"
    configure_rx: true

    # GNSS/INS Parameters
    frame_id: dgps_main_antenna
    poi_frame_id: base_link
    aux1_frame_id: dgps_aux_antenna
    vehicle_frame_id: base_link
    get_spatial_config_from_tf: true
    lock_utm_zone: true
    use_ros_axis_orientation: true
    receiver_type: gnss
    multi_antenna: true
    datum: WGS84

    ant_type: "Unknown"
    ant_serial_nr: "Unknown"
    ant_aux1_type: "Unknown"
    ant_aux1_serial_nr: "Unknown"

    polling_period:
      pvt: 100
      rest: 100

    # time
    use_gnss_time: false
    ntp_server: false
    ptp_server_clock: false
    latency_compensation: true

    # RTK
    rtk_settings:
      ntrip_1:
        id: "NTR1"
        caster: ""
        caster_port: 2101
        username: ""
        password: ""
        mountpoint: ""
        version: "v2"
        tls: false
        fingerprint: ""
        rtk_standard: "auto"
        send_gga: "auto"
        keep_open: true

    publish:
      aimplusstatus: true
      attcoveuler: true
      atteuler: true
      diagnostics: true
      extsensormeas: true
      gpgga: true
      gpgsa: true
      gpgsv: true
      gprmc: true
      gpsfix: true
      gpst: true
      measepoch: true
      navsatfix: true
      poscovcartesian: true
      poscovgeodetic: true
      pose: true
      pvtcartesian: true
      pvtgeodetic: true
      tf: false
      tf_ecef: false
      twist: true
      velcovcartesian: true
      velcovgeodetic: true

    activate_debug_log: false